spring:
  application:
    name: iupiBackend
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
  sql:
    init:
      schema-locations: classpath:import.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8090
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  duration: ${JWT_DURATION}
logging:
  level:
    org.springframework: error