spring:
  application:
    name: iupiBackend
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
  sql:
    init:
      schema-locations: classpath:import.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/auth/oauth2/login/success"
            authorization-grant-type: authorization_code
            client-authentication-method: post
          apple:
            client-id: YOUR_APPLE_CLIENT_ID
            client-secret: YOUR_APPLE_CLIENT_SECRET
            scope: name, email
            redirect-uri: "{baseUrl}/auth/oauth2/login/success"
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: email
server:
  port: 8090
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  duration: ${JWT_DURATION}
logging:
  level:
    org.springframework: error